version: '3.1'

services:

#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_DB: GoogleForms
#      POSTGRES_USER: rynal
#      POSTGRES_PASSWORD: 1q2w3e4r
#    ports:
#      - 5432:5432
  msdb:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: 1433
    ports:
      - 1400:1433
